### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 3Fendi3** [ShaneBeee/SkBee#378] opened 2023-04-14 15:55 UTC
**Describe the bug**   
I get an error when starting the server

**To Reproduce**   
enabling the server on 1.19.4

**Expected behavior**   
that the add-on will load

**Screenshots/Errors**   
[17:53:26 INFO]: [SkBee] Enabling SkBee v2.8.3
[17:53:26 INFO]: [SkBee] Loading NBTApi...
[17:53:26 INFO]: [SkBee] [NBTAPI] Found Spigot: v1_19_R3! Trying to find NMS support
[17:53:26 INFO]: [SkBee] [NBTAPI] NMS support 'MC1_19_R3' loaded!
[17:53:26 INFO]: [SkBee] Successfully loaded NBTApi!
[17:53:26 INFO]: [SkBee] NBT Elements successfully loaded
[17:53:26 INFO]: [SkBee] Recipe Elements successfully loaded
[17:53:26 INFO]: [SkBee] Scoreboard Elements successfully loaded
[17:53:26 INFO]: [SkBee] Scoreboard Objective Elements successfully loaded
[17:53:26 INFO]: [SkBee] Team Elements successfully loaded
[17:53:26 INFO]: [SkBee] Bound Elements successfully loaded
[17:53:26 INFO]: [SkBee] Text Component Elements successfully loaded
[17:53:26 INFO]: [SkBee] Pathfinding Elements successfully loaded
[17:53:26 INFO]: [SkBee] Structure Elements successfully loaded
[17:53:27 INFO]: [SkBee] Other Elements successfully loaded
[17:53:27 INFO]: [SkBee] Virtual Furnace Elements disabled via config
[17:53:27 INFO]: [SkBee] World Creator Elements successfully loaded
[17:53:27 INFO]: [SkBee] Game Event Elements successfully loaded
[17:53:27 INFO]: [SkBee] BossBar Elements successfully loaded
[17:53:27 INFO]: [SkBee] Statistic Elements successfully loaded
[17:53:27 INFO]: [SkBee] Villager Elements successfully loaded
[17:53:27 INFO]: [SkBee] Advancement Elements successfully loaded
[17:53:27 INFO]: [SkBee] World Border Elements successfully loaded
[17:53:27 INFO]: [SkBee] Particle Elements successfully loaded
[17:53:27 INFO]: [SkBee] Minecraft Tag elements successfully loaded
[17:53:27 INFO]: [SkBee] RayTrace elements successfully loaded
[17:53:27 INFO]: [SkBee] Fishing elements successfully loaded
[17:53:27 ERROR]: Error occurred while enabling SkBee v2.8.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:495) ~[?:?]
        at java.lang.Class.forName(Class.java:474) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117) ~[Skript-2.6.4.jar:?]
        at com.shanebeestudios.skbee.AddonLoader.loadDisplayEntityElements(AddonLoader.java:498) ~[SkBee-2.8.3.jar:?]
        at com.shanebeestudios.skbee.AddonLoader.loadSkriptElements(AddonLoader.java:103) ~[SkBee-2.8.3.jar:?]
        at com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:55) ~[SkBee-2.8.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1959]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 19 more
[17:53:27 INFO]: [SkBee] Disabling SkBee v2.8.3

**Version Info:**
```
purpur 1.19.4 java 19
```

**Additional context**   
this disables all scripts

**Comment by ShaneBeee** [comment] 2023-04-14 15:56
Duplicate of #377

**Closed by ShaneBeee** 2023-04-14 15:56 UTC
