### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Selvati** [ShaneBeee/SkBee#87] opened 2020-12-28 02:52 UTC
**Describe the bug**
I'm not able to correctly use `set tag "EXAMPLE" of nbt of player's tool to "EXAMPLE"`, I am new to using SkBee so hopefully this is actually just a bug and not me misusing/misunderstanding the proper use of the syntax. But from what little information I have read on the docs, and the fact that there are no errors when loading the script, I am assuming it's a bug.
(Not able to set a tag of nbt data to a string/value)

**To Reproduce**
To reproduce my issue you can create a new .sk file and insert the following and then load into your server and try running the "/ex1" command to get yourself a paper item with custom nbt tag "test" with data value of "test1", you can then rightclick while holding the paper item to get a broadcast of the current data of the custom "test" nbt tag, and in my code I have it set to change the values back and forth on rightclick, from "test1" to "test2" and broadcast the nbt data value for troubleshooting.
```vb
command /ex1:
	trigger:
		give paper with nbt "{test:[test1]}" to player

on right click:
	player's held item is paper:
		if tag "test" of nbt of player's tool is not "":
			set {_tag} to tag "test" of nbt of player's tool
			if tag "test" of nbt of player's tool is  "test1":
				broadcast {_tag}
				set tag "test" of nbt of player's tool to "test2"
				stop
			if tag "test" of nbt of player's tool is  "test2":
				broadcast {_tag}
				set tag "test" of nbt of player's tool to "test1"
				stop
```

**Expected behavior**
In theory, if I am understanding the proper use of `set tag "EXAMPLE" of nbt of player's tool to "EXAMPLE"`, it should set/replace/update the given nbt tag to the given value, in this case it should update the custom nbt tag on the paper item from "test1" to "test2", but unfortunately it does not. I am not 100% sure this is its intended feature, but if it is a bug I hope I help bring it to light, and if it's not intended to function as I thought, it would be a great suggestion for future updates.

**Screenshots/Errors**
No screenshots or errors to show, it's pretty basic, everything loads and functions properly except for updating/setting the values.

**Version Info:**
 - **SkBee Version:** "SkBee v1.9.1"
-  **Skript Version:** "Skript v2.5.3"
 - **Server Version/Platform** "Paper version git-Paper-332 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)"

**Additional context**
N/A

**Comment by ShaneBeee** [comment] 2021-01-03 04:25
This is not a bug. This is just how NBT works.
<img width="958" alt="Screen Shot 2021-01-02 at 8 24 46 PM" src="https://user-images.githubusercontent.com/20008482/103471749-acf24d00-4d38-11eb-9bf9-71dc430c3473.png">

**Comment by ShaneBeee** [comment] 2021-01-12 01:41
Closing as this is not an issue.

**Closed by ShaneBeee** 2021-01-12 01:41 UTC
