### ISSUE TITLE
Grabbing NBT during On Death event throws console error

### ISSUE THREAD

**Issue by YourMCAdmin** [ShaneBeee/SkBee#28] opened 2020-06-07 16:33 UTC
Great add on, I love it!
I noticed a big bad console error when I grab nbt data from a victim during on on death event. However, the code works lol. I am able to grab nbt data from a victim, so I'm not 100% sure what the error is about. 

```
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[12:27:28] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:27:28] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:27:28] [Server thread/ERROR]: #!#! Here is full list of them:
[12:27:28] [Server thread/ERROR]: #!#! skript-mirror (https://github.com/btk5h/skript-mirror) SkRecipe (https://github.com/ShaneBeee/SkRecipe) SkBee skUtilities (https://tim740.github.io/) skript-yaml SkQuery 
[12:27:28] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:27:28] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:27:28] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:27:28] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:27:28] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:27:28] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! Stack trace:
[12:27:28] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Entity can't be null/dead!
[12:27:28] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.NBTEntity.<init>(NBTEntity.java:28)
[12:27:28] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBTApi.getNBT(NBTApi.java:130)
[12:27:28] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.convert(ExprObjectNBT.java:44)
[12:27:28] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.convert(ExprObjectNBT.java:18)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:391)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:382)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:55)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[12:27:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[12:27:28] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:27:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:27:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[12:27:28] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:767)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityWolf.B(EntityWolf.java:253)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.a(SourceFile:139)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.e(SourceFile:131)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:150)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:686)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2609)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityAgeable.movementTick(EntityAgeable.java:171)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityAnimal.movementTick(EntityAnimal.java:28)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityWolf.movementTick(EntityWolf.java:151)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2396)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityWolf.tick(EntityWolf.java:167)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:806)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.World.a(World.java:879)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:531)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1319)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173)
[12:27:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
[12:27:28] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! Version Information:
[12:27:28] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (latest)
[12:27:28] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[12:27:28] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[12:27:28] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[12:27:28] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[12:27:28] [Server thread/ERROR]: #!#!   Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
[12:27:28] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.9.0-9-amd64
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! Server platform: Paper
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! Current node: null
[12:27:28] [Server thread/ERROR]: #!#! Current item: set {_nbt}(as java.lang.Object) to the object nbt of the attacked entity
[12:27:28] [Server thread/ERROR]: #!#! Current trigger: death (death/spawn) (tag_awe.sk, line 20)
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! Thread: Server thread
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! Language: english
[12:27:28] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[12:27:28] [Server thread/ERROR]: #!#! 
[12:27:28] [Server thread/ERROR]: #!#! End of Error.
[12:27:28] [Server thread/ERROR]: #!#! 
```

**Comment by ShaneBeee** [comment] 2020-06-07 20:19
Duplicate of #21

**Closed by ShaneBeee** 2020-06-07 20:19 UTC

**Comment by Chew** [comment] 2020-06-29 21:59
Doesn't seem like a duplicate. Evidently it works, but it still throws the error.
