### ISSUE TITLE
[BUG] Throws Error when using "clone

### ISSUE THREAD

**Issue by RedstonePlays** [ShaneBeee/SkBee#118] opened 2021-11-18 05:51 UTC
**Describe the bug**

**To Reproduce**
Please include clear steps to reproduce the behavior

**Expected behavior**

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.

**Version Info:**
 - **SkBee Version:** (ex: 1.0.0)
-  **Skript Version:** (ex: Skript 2.5-alpha3)
 - **Server Version/Platform** (ex: Spigot 1.15.2)

**Additional context**

**Comment by ShaneBeee** [comment] 2021-11-18 15:26
Closing due to lack of information.
None of the template was actually filled in. I can't triage an issue if I dont know what the issue is

**Closed by ShaneBeee** 2021-11-18 15:26 UTC
