### ISSUE TITLE
[BUG] displayed red?

### ISSUE THREAD

**Issue by BrianTheVoid** [ShaneBeee/SkBee#155] opened 2022-04-08 16:10 UTC
when i do /pl, its displayed red, any line of code with any skbee feature breaks the whole file its in, and now my skript wont work.

I expected it to work..?

**Version Info:**
 - **SkBee Version:** 1.15.2
-  **Skript Version:** 2.6.3
 - **Server Version/Platform** Paper 1.16.5
 
 Log:
 
 [16:02:08 ERROR]: Error occurred while enabling SkBee v1.15.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/translation/Translatable
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
	at com.shanebeestudios.skbee.SkBee.loadTextElements(SkBee.java:210) ~[?:?]
	at com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:104) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.translation.Translatable
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 15 more

**Comment by ShaneBeee** [comment] 2022-04-08 20:55
duplicate of #151

**Closed by ShaneBeee** 2022-04-08 20:55 UTC
