### ISSUE TITLE
[BUG] Chunk Generator stops working after restart

### ISSUE THREAD

**Issue by eeggeegg** [ShaneBeee/SkBee#680] opened 2024-07-20 12:39 UTC
### What happened?

Restarting after setting up a chunk generator on a new world will start generating normal chunks.

### Steps to reproduce

1. Create a new world with a chunk generator & make sure it works.
2. Restart the server.
3. Generate new chunks.

### Expected behavior

The server should restart and continue generating chunks using the custom chunk generator.

### SkBee Version

3.5.7

### Server Version

Paper 1.20.6

### SkBee Info

[12:37:33 INFO]: --- [SkBee Loading Info] ---
[12:37:33 INFO]: - [NBTAPI] Found Minecraft: 1.20.6! Trying to find NMS support
[12:37:33 INFO]: - [NBTAPI] NMS support 'MC1_20_R4' loaded!
[12:37:33 INFO]: - NBT Elements successfully loaded
[12:37:33 INFO]: - Text Component Elements successfully loaded
[12:37:33 INFO]: - Advancement Elements successfully loaded
[12:37:33 INFO]: - BossBar Elements successfully loaded
[12:37:33 INFO]: - Bound Elements successfully loaded
[12:37:33 INFO]: - Damage Source elements successfully loaded
[12:37:33 INFO]: - Display Entity elements successfully loaded
[12:37:33 INFO]: - Fishing elements successfully loaded
[12:37:33 INFO]: - Game Event Elements successfully loaded
[12:37:33 INFO]: - Particle Elements successfully loaded
[12:37:33 INFO]: - RayTrace elements successfully loaded
[12:37:33 INFO]: - Recipe Elements successfully loaded
[12:37:33 INFO]: - Scoreboard Elements successfully loaded
[12:37:33 INFO]: - Scoreboard Objective Elements successfully loaded
[12:37:33 INFO]: - Statistic Elements successfully loaded
[12:37:33 INFO]: - Structure Elements successfully loaded
[12:37:33 INFO]: - Minecraft Tag elements successfully loaded
[12:37:33 INFO]: - Team Elements successfully loaded
[12:37:33 INFO]: - Tick Manager elements successfully loaded
[12:37:33 INFO]: - Villager Elements successfully loaded
[12:37:33 INFO]: - Virtual Furnace Elements disabled via config
[12:37:33 INFO]: - World Border Elements successfully loaded
[12:37:33 INFO]: - World Creator Elements successfully loaded
[12:37:33 INFO]: - Chunk Generator Elements successfully loaded
[12:37:33 INFO]: - Plugin is up to date!
[12:37:33 INFO]: --- [Server Info] ---
[12:37:33 INFO]: Server Version: 1.20.6-148-20f5165 (MC: 1.20.6)
[12:37:33 INFO]: Skript Version: 2.9.0
[12:37:33 INFO]: Skript Addons:
[12:37:33 INFO]: - skNoise v1.0
[12:37:33 INFO]: - skript-gui v1.3
[12:37:33 INFO]: - DiSky v4.12.2-beta1
[12:37:33 INFO]: - skript-particle v1.3.1
[12:37:33 INFO]: - skript-reflect v2.4
[12:37:33 INFO]: - SkQuery v4.1.10
[12:37:33 INFO]: SkBee Version: 3.5.7
[12:37:33 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment] 2024-07-20 17:07
I cannot reproduce.
I have written several chunk generators and they've always generated the chunks.

Without you providing any code to reproduce, there's really nothing I can check here.

**Comment by eeggeegg** [comment] 2024-07-21 20:52
Can I see your code?

**Comment by ShaneBeee** [comment] 2024-07-22 15:41
this is the current one im testing, and have had no issue:
https://github.com/ShaneBeee/SkriptSnippets/blob/master/snippets/chunkgenerator/mars.sk

**Comment by ShaneBeee** [comment] 2024-07-23 19:53
question, in the skbee config do you have this set to true:
`auto-load-custom-worlds: true`
if you do, set it to false.

**Comment by eeggeegg** [comment] 2024-07-23 20:05
Yep! That was it, thanks!

**Comment by ShaneBeee** [comment] 2024-07-23 20:05
ok good, thanks.
Ill force it to false when a generator is set.

(re-opening... ill close it when I release the change)

**Closed** 2024-07-29 17:05 UTC
Labels: bug :lady_beetle:, completed 👍
