### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SJ-Tom** [ShaneBeee/SkBee#560] opened 2024-01-21 15:07 UTC
### What happened?

If you create a world with multiverse than you need to restart the server in order to use https://skripthub.net/docs/?id=4445 and the world have been found. Also, on deleting then the world still seems to exist according to skbee. A live update is missing when worlds are created and deleted

### Steps to reproduce

1. create or delete a world
2. then query https://skripthub.net/docs/?id=4445 
3. world seems not existing after created or still existing after deleted

### Expected behavior

The query https://skripthub.net/docs/?id=4445 check live if the world is there and shows it correctly

### SkBee Version

3.0.2

### Server Version

Paper-1.20.4

### SkBee Info

[16:04:51] [Render thread/INFO]: [System] [CHAT] --- [SkBee Loading Info] ---
[16:04:51] [Render thread/INFO]: [System] [CHAT] - [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
[16:04:51] [Render thread/INFO]: [System] [CHAT] - [NBTAPI] NMS support 'MC1_20_R3' loaded!
[16:04:51] [Render thread/INFO]: [System] [CHAT] - NBT Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Text Component Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Advancement Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - BossBar Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Bound Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Display Entity elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Fishing elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Game Event Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Particle Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - RayTrace elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Recipe Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Scoreboard Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Scoreboard Objective Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Statistic Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Structure Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Minecraft Tag elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Team Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Villager Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - Virtual Furnace Elements disabled via config
[16:04:51] [Render thread/INFO]: [System] [CHAT] - World Border Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] - World Creator Elements successfully loaded
[16:04:51] [Render thread/INFO]: [System] [CHAT] --- [Server Info] ---
[16:04:51] [Render thread/INFO]: [System] [CHAT] Server Version: git-Paper-346 (MC: 1.20.4)
[16:04:51] [Render thread/INFO]: [System] [CHAT] Skript Version: 2.7.3
[16:04:51] [Render thread/INFO]: [System] [CHAT] Skript Addons:
[16:04:51] [Render thread/INFO]: [System] [CHAT] - skript-reflect v2.4
[16:04:51] [Render thread/INFO]: [System] [CHAT] - skript-db v1.3.9
[16:04:51] [Render thread/INFO]: [System] [CHAT] SkBee Version: 3.0.2
[16:04:51] [Render thread/INFO]: [System] [CHAT] SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

I have tried it with several different world managers and with the integrated skbee delete world file

**Comment by ShaneBeee** [comment] 2024-01-21 17:36
that condition checks if the directory contains a `level.dat` file, thus proving the file is a world.
At the time a world is created, that file is not created until the world processes its first save (whether every 5 minutes or on shutdown)

If you're creating a world with MV, obviously that directory is made, why are you checking if its made?
Since you're loading the world, just check if the world itself is loaded, ie `if world "world" is set:`

Closing this as a non-issue since everything is working as intended.

**Closed by ShaneBeee** 2024-01-21 17:36 UTC

**Comment by SJ-Tom** [comment] 2024-01-21 17:38
Oh, ok, can I then save the world right after creating to fix this issue or do I need to do something else?

**Comment by ShaneBeee** [comment] 2024-01-21 17:38
a) yes, you can save it right after
b) I literally gave you an option that should work
