### ISSUE TITLE
[BUG] On player change armor event

### ISSUE THREAD

**Issue by samthecoder1235** [ShaneBeee/SkBee#319] opened 2023-01-11 10:00 UTC
**Describe the bug**   
The event is triggered when it shouldn't be supposed to.
Same issue with the other armor change event.

**To Reproduce**   
1. Use this code
on player armor change:
    send "test" to player
2. Wear a breakable piece of armor and get it damaged by an entity.
3. This event triggers when it shouldn't.

**Expected behavior**   
As read from the docs, it should be called when the player themselves changes the armor. So, the event shouldn't trigger when another entity damages the player's armor. 

**Screenshots/Errors**   
![Screenshot 2023-01-11 014306](https://user-images.githubusercontent.com/120090595/211774593-ad57a6cd-1eca-447c-99cd-6a06be2738bf.png)
No errors.
**Version Info:**
```
Please provide output of '/skbee info' here!
```
![2023-01-11_01 59 40](https://user-images.githubusercontent.com/120090595/211775320-07c92abc-c87b-45a1-b7b8-1d2241349269.png)

**Additional context**   
The docs are misleading and because of that it should be considered a bug and should be fixed.

**Comment by ShaneBeee** [comment] 2023-01-11 13:31
1) You aren't even using SkBee's event, and you are reporting it to me?
<img width="406" alt="Screenshot 2023-01-11 at 5 27 21 AM" src="https://user-images.githubusercontent.com/20008482/211818259-5bd66207-38af-41ac-90e3-45b56ed99047.png">

2) I wrote some code to check SkBee's event, Skript's event (the one you are using in your code) and an import of the event directly from paper:
```vb
on player armor change:
	broadcast "&aSkript armor change"

on player change armor:
	broadcast "&bSkBee armor change"

import:
	com.destroystokyo.paper.event.player.PlayerArmorChangeEvent

on PlayerArmorChangeEvent:
	broadcast "&cPaper armor change"
```
And the outcome shows me that this happens on all 3:
<img width="966" alt="Screenshot 2023-01-11 at 5 29 14 AM" src="https://user-images.githubusercontent.com/20008482/211818676-bb2b2ccd-34a2-4b4a-9000-e8467d498f07.png">

What this tells me is that the issue is server sided.

**Comment by samthecoder1235** [comment] 2023-01-12 00:19
What should I do then?

**Comment by ShaneBeee** [comment] 2023-01-12 00:54
Your best bet is to ask for help on skUnity's Discord.

Anyways I'll be closing this issue as it is not an SkBee issue.

**Closed by ShaneBeee** 2023-01-12 00:54 UTC
Labels: non SkBee issue
