### ISSUE TITLE
[BUG] 'showing itemtype' requires MC 1.18.2+

### ISSUE THREAD

**Issue by GeoGb1** [ShaneBeee/SkBee#295] opened 2022-12-11 16:19 UTC
**Describe the bug**   
The code is simply not working

**To Reproduce**   
-

**Expected behavior**   
-

**Screenshots/Errors**   
![image](https://user-images.githubusercontent.com/92254228/206915265-96544eab-46e2-4282-918f-ce71e173dc4e.png)

**Version Info:**
![image](https://user-images.githubusercontent.com/92254228/206915312-1d83e5ba-2bd5-4db6-b9aa-1a23636e7360.png)
![image](https://user-images.githubusercontent.com/92254228/206915316-8ced82f5-4a29-4d6b-bbc3-0aa05d331c5f.png)

**Additional context**   
I use this event in one of my skripts and it used to work until i updated skbee to the latest version

**Comment by ShaneBeee** [comment] 2022-12-11 16:49
I don't understand the issue here.
You are running a 1.17.1 server
The error tells you this code requires 1.18.2....

Is that not blatantly obvious that you need a higher server version for said code?

**Comment by GeoGb1** [comment] 2022-12-11 17:16
> I don't understand the issue here. You are running a 1.17.1 server The error tells you this code requires 1.18.2....
> 
> Is that not blatantly obvious that you need a higher server version for said code?

I thought its only an error since that thing used to work in the verion i used before. 
Can you tell me which is the last version that allows me to use that on 1.17.1?

**Comment by ShaneBeee** [comment] 2022-12-11 17:40
I honestly don't know.
You'd have to check back in the change logs for when I switched text components to use Paper's AdventureAPI
That's the reason it no longer works on 1.17.x
I recommend just updating your server.

Anyways I'm closing the issue as its not a bug.

**Closed by ShaneBeee** 2022-12-11 17:40 UTC
