### ISSUE TITLE
[BUG] On player purchase not working

### ISSUE THREAD

**Issue by not-3than** [ShaneBeee/SkBee#441] opened 2023-07-16 03:10 UTC
### What happened?

I'm trying to use on player purchase: to track when a player trades with one of my shopkeepers (villagers), but the event isn't firing for some reason.

### Steps to reproduce

1. Use 1.18.2 Paper with SkBee 2.15.0 (though I believe this happens on all versions)
2. Try using on player purchase: event, and nothing will fire
3. I was using it on villagers from Shopkeepers plugin and normal villagers, no changes

### Expected behavior

I expected the event to fire and tell me what item was traded for and such, but nothing was happening.

### SkBee Version

2.5.10

### Server Version

Paper 1.18.2

### SkBee Info

[03:09:03 INFO]: --- [SkBee Loading Info] ---
[03:09:03 INFO]: - Other Elements successfully loaded
[03:09:03 INFO]: - [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
[03:09:03 INFO]: - [NBTAPI] NMS support 'MC1_18_R2' loaded!
[03:09:03 INFO]: - NBT Elements successfully loaded
[03:09:03 INFO]: - Text Component Elements successfully loaded
[03:09:03 INFO]: - Advancement Elements successfully loaded
[03:09:03 INFO]: - BossBar Elements successfully loaded
[03:09:03 INFO]: - Bound Elements successfully loaded
[03:09:03 INFO]: - Display Entity elements disabled (Requires Minecraft 1.19.4+)
[03:09:03 INFO]: - Fishing elements successfully loaded
[03:09:03 INFO]: - Game Event Elements successfully loaded
[03:09:03 INFO]: - Particle Elements successfully loaded
[03:09:03 INFO]: - Particle Elements successfully loaded
[03:09:03 INFO]: - RayTrace elements successfully loaded
[03:09:03 INFO]: - Recipe Elements successfully loaded
[03:09:03 INFO]: - Scoreboard Elements successfully loaded
[03:09:03 INFO]: - Scoreboard Objective Elements successfully loaded
[03:09:03 INFO]: - Statistic Elements successfully loaded
[03:09:03 INFO]: - Structure Elements successfully loaded
[03:09:03 INFO]: - Minecraft Tag elements successfully loaded
[03:09:03 INFO]: - Team Elements successfully loaded
[03:09:03 INFO]: - Villager Elements successfully loaded
[03:09:03 INFO]: - Virtual Furnace Elements disabled via config
[03:09:03 INFO]: - World Border Elements successfully loaded
[03:09:03 INFO]: - World Creator Elements successfully loaded
[03:09:03 INFO]: - Checking for update failed!
[03:09:03 INFO]: - Checking for update failed!
[03:09:03 INFO]: - Checking for update failed!
[03:09:03 INFO]: - Checking for update failed!
[03:09:03 INFO]: --- [Server Info] ---
[03:09:03 INFO]: Server Version: git-Paper-372 (MC: 1.18.2)
[03:09:03 INFO]: Skript Version: 2.6.3
[03:09:03 INFO]: Skript Addons:
[03:09:03 INFO]: - skript-placeholders v1.5.2
[03:09:03 INFO]: - skript-gui v1.3
[03:09:03 INFO]: - DiSky v4.7.0
[03:09:03 INFO]: - MorkazSk v1.3
[03:09:03 INFO]: - skript-reflect v2.3
[03:09:03 INFO]: - skRayFall v1.9.28
[03:09:03 INFO]: SkBee Version: 2.15.0
[03:09:03 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

I haven't tested it on any other version / server yet. I don't believe it's any other plugins I have interfering with it but I'm not sure. It could be Shopkeepers, as that's the only plugin that deals with villager trades.

**Comment by Fusezion** [comment] 2023-07-16 03:11
So by shopkeepers you mean the plugin right

**Comment by Fusezion** [comment] 2023-07-16 03:12
Shopkeepers has their own internal event for purchasing this is just something they did, I don't really plan to add their api into skbee so your best resort is to make use of skript-reflect and grab their event yourself

**Comment by ShaneBeee** [comment] 2023-07-16 03:12
works fine for me:
```vb
on player purchase:
	broadcast "PURCHASE: %player%"
```
<img width="966" alt="Screenshot 2023-07-15 at 8 12 15 PM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/7cce7ed7-d037-4c0c-9ffa-2b739827f25d">

**Comment by Fusezion** [comment] 2023-07-16 03:13
normal villager or shopkeeper plugin villager shane?

**Comment by ShaneBeee** [comment] 2023-07-16 03:13
normal villager

**Comment by Fusezion** [comment] 2023-07-16 03:15
that'll be why, old skunity issue on help channel, someone was using skbee's but had to use reflect and use shopkeeper's event due to them 

if you're apart of the SkUnity discord this will link to the discussion at the time, I don't believe we provided any code tho
https://discord.com/channels/135877399391764480/138027100593455104/1105334587095261275

**Comment by Fusezion** [comment] 2023-07-16 03:20
Added non skbee issue as it should just be caused by the limitation of shopkeepers

**Comment by not-3than** [comment] 2023-07-16 04:03
Weird. I tested with normal villagers and with shopkeeper produced villagers, Shopkeepers must mess with all villager trade events. Weird.
I'm not familiar with looking up libraries and such, what is the information from Shopkeepers called that I need in order to find what the event is called? I'm sort of familiar with reflect but not familiar enough.

**Comment by not-3than** [comment] 2023-07-16 04:18
Ah, nevermind. Found it. Thanks guys.

**Comment by ShaneBeee** [comment] 2023-07-16 04:19
closing as this isn't an SkBee issue

**Closed by ShaneBeee** 2023-07-16 04:19 UTC
Labels: non SkBee issue 🤬
