### ISSUE TITLE
[BUG] Team unregister console error

### ISSUE THREAD

**Issue by Gabqb** [ShaneBeee/SkBee#347] opened 2023-02-18 13:42 UTC
whenever I try to unregister a team from a loop-value from looping a list I get a console error

use this code to find error
https://paste.md-5.net/hecuxizeqi.coffeescript

the team is unregistered and i don't get error

https://paste.md-5.net/dupominihu.md

**Version Info:**
![image](https://user-images.githubusercontent.com/103600594/219869019-c83d86a6-12e1-49b8-b49f-0fde41d2f9b1.png) 
![image](https://user-images.githubusercontent.com/103600594/219869031-708b2730-8c65-4589-b3b5-2924c9596145.png)

**Comment by ShaneBeee** [comment] 2023-02-18 16:21
can you show some code where the teams are registered as well as when that variable is set.

Based on what you have provided, I tried a bit of code and it didn't cause any errors.

**Comment by Gabqb** [comment] 2023-02-18 20:08
Function CreateTeam(p:player):
	register new team "party::%{_p}%"
	send "&aParty created" to {_p}
	set (metadata tag "Leader" of {_p}) to true
	add team named "party::%{_p}%" to {Parties::*}
	add {_p} to team entries of team named "party::%{_p}%"
	set allow friendly fire team state of team named "party::%{_p}%" to false
Function DeleteParties():
	loop {Parties::*}:
		unregister team loop-value
		set {_} to loop-value
		#replace all "party::" in {_} with ""
		broadcast {_}
		set (metadata tag "Leader" of ("%{_}%" parsed as offline player)) to false
	delete {Parties::*}

**Comment by Gabqb** [comment] 2023-02-18 20:09
https://paste.md-5.net/napemavoxa.coffeescript

**Comment by ShaneBeee** [comment] 2023-02-18 20:16
Looks like you are trying to save the team:
<img width="854" alt="Screenshot 2023-02-18 at 12 13 09 PM" src="https://user-images.githubusercontent.com/20008482/219891808-90368214-5dae-40f4-a0eb-fba92b1d68c9.png">
<img width="674" alt="Screenshot 2023-02-18 at 12 13 26 PM" src="https://user-images.githubusercontent.com/20008482/219891821-f9207481-4866-4734-86bd-53ee8e3f827a.png">

You can't save a team, so rather just save the name/id of the team!

That said, running your code I get no errors.

**Comment by Gabqb** [comment] 2023-02-18 20:18
alright

**Comment by ShaneBeee** [comment] 2023-02-23 03:30
Closing as I could not reproduce said error, as well it appeared to be user error

**Closed by ShaneBeee** 2023-02-23 03:30 UTC
Labels: waiting on reply
