### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GalaxyGamingFR** [ShaneBeee/SkBee#713] opened 2024-08-28 10:57 UTC
### What happened?

<img width="262" alt="Screenshot 2024-08-28 at 3 55 19 AM" src="https://github.com/user-attachments/assets/6c55215f-b2d9-4c10-9c8a-79ab17196ec9">
Sword's flags won't go away

### Steps to reproduce

1. Give yourself any tool
2. Run the effect command !set me's tool to me's tool with all item flags

### Expected behavior

<img width="253" alt="Screenshot 2024-08-28 at 3 56 39 AM" src="https://github.com/user-attachments/assets/8ddbe6a3-337b-4427-87af-0fea2abdaefa">
Everything in the lore shouldn't be there

### SkBee Version

3.6.1

### Server Version

Purpur 1.21.1

### SkBee Info

<img width="429" alt="Screenshot 2024-08-28 at 3 57 15 AM" src="https://github.com/user-attachments/assets/1538c5df-328c-42b2-b327-31beda680e1b">

**Comment by Fusezion** [comment] 2024-08-28 19:35
I am gonna close this a duplicate of https://github.com/ShaneBeee/SkBee/issues/685 and https://github.com/ShaneBeee/SkBee/issues/702 which both have been marked as non skbee issue.

I suggest checking out #685 for a mildly detailed response for what changed

**Closed by Fusezion** 2024-08-28 19:35 UTC
