### ISSUE TITLE
[BUG] Text component send title enforces fade in

### ISSUE THREAD

**Issue by AsleeppMC** [ShaneBeee/SkBee#542] opened 2023-12-24 16:11 UTC
### What happened?

Due to having a custom title transition-type thing, I noticed then when using `send title component... with fade out 1 second` or `send title component... with fade in 0 second and fade out 1 second` that it seems to enforce the fade, when its supposed to get rid of it? This works in the normal /title command.

### Steps to reproduce

1. use either `send title component... with fade out 1 second` or `send title component... with fade in 0 second and fade out 1 second`

### Expected behavior

For fade to be gone when fade in is at 0 seconds.

### SkBee Version

3.0.1

### Server Version

Purpur 1.20.1

### SkBee Info

17:11:18 [INFO] --- [SkBee Loading Info] ---
17:11:18 [INFO] - [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
17:11:18 [INFO] - [NBTAPI] NMS support 'MC1_20_R1' loaded!
17:11:18 [INFO] - NBT Elements successfully loaded
17:11:18 [INFO] - Text Component Elements successfully loaded
17:11:18 [INFO] - Advancement Elements successfully loaded
17:11:18 [INFO] - BossBar Elements successfully loaded
17:11:18 [INFO] - Bound Elements successfully loaded
17:11:18 [INFO] - Display Entity elements successfully loaded
17:11:18 [INFO] - Fishing elements successfully loaded
17:11:18 [INFO] - Game Event Elements successfully loaded
17:11:18 [INFO] - Particle Elements successfully loaded
17:11:18 [INFO] - RayTrace elements successfully loaded
17:11:18 [INFO] - Recipe Elements successfully loaded
17:11:18 [INFO] - Scoreboard Elements successfully loaded
17:11:18 [INFO] - Scoreboard Objective Elements successfully loaded
17:11:18 [INFO] - Statistic Elements successfully loaded
17:11:18 [INFO] - Structure Elements successfully loaded
17:11:18 [INFO] - Minecraft Tag elements successfully loaded
17:11:18 [INFO] - Team Elements successfully loaded
17:11:18 [INFO] - Villager Elements successfully loaded
17:11:18 [INFO] - Virtual Furnace Elements disabled via config
17:11:18 [INFO] - World Border Elements successfully loaded
17:11:18 [INFO] - World Creator Elements successfully loaded
17:11:18 [INFO] --- [Server Info] ---
17:11:18 [INFO] Server Version: git-Purpur-2062 (MC: 1.20.1)
17:11:18 [INFO] Skript Version: 2.7.3
17:11:18 [INFO] Skript Addons:
17:11:18 [INFO] - skript-placeholders v1.5.2
17:11:18 [INFO] - skript-reflect v2.3.1-for-Skript-2.7
17:11:18 [INFO] - ItemsAdder v3.6.2-beta-r4
17:11:18 [INFO] SkBee Version: 3.0.1
17:11:18 [INFO] SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment] 2023-12-24 17:10
didn't you already report title stuff #539

**Comment by AsleeppMC** [comment] 2023-12-24 17:25
oh should I just've replied to that one?

**Comment by ShaneBeee** [comment] 2023-12-24 17:26
I have a feeling this issue is already fixed when I fixed the other one.
Ill send you a jar on discord in a minute to have you test

**Comment by ShaneBeee** [comment] 2023-12-24 19:00
duplicate of #539

**Closed by ShaneBeee** 2023-12-24 19:00 UTC
