### ISSUE TITLE
Team Color (Glows)

### ISSUE THREAD

**Issue by twmorris1** [ShaneBeee/SkBee#16] opened 2020-05-05 14:02 UTC
****
All Colored Glows are broken. I was checking issues and saw a guy mentioned this before and our server is having some of the same issues.

**To Reproduce**
Install SkBee v1.3.0 on Spigot/Paper 1.15.2
Run following commands: 
/team add red 
/team modify red color red
/team join cyan %player%
apply glowing to yourself

**Expected behavior**
The player should glow the color their team is set to but the color is just defaulted to white when this plugin is installed. 

**Screenshots/Errors**
No errors, and I believe the information is pretty straight forward.

**Version Info:**
 - SkBee Version:1.3.0)
-  Skript 2.5-alpha3)
 - Spigot 1.15.2

**Comment by ShaneBeee** [comment] 2020-05-05 22:58
Try disabling scoreboards in the SkBee config. 
I think the issue is the fact that the players are given a different scoreboard than the main server scoreboard, therefor they aren't properly joining the teams.

**Comment by ShaneBeee** [comment] 2020-07-08 09:34
Closing due to no reply. Im assuming the issue has been resolved?!?!

**Closed by ShaneBeee** 2020-07-08 09:34 UTC

**Comment by TheGeekGamer91** [comment] 2021-01-18 17:47
Hello, sorry for reopening an old ticket, but what can be done if one uses skbee scoreboards and if we also want to use the minecraft vanilla teams for the glowing ?

Thanks in advance.
