### ISSUE TITLE
[BUG] Critical issue with 1.18.x

### ISSUE THREAD

**Issue by not-3than** [ShaneBeee/SkBee#460] opened 2023-08-03 01:30 UTC
### What happened?

SkBee won't load since 1.18.x is missing a certain class

### Steps to reproduce

1. Load SkBee 2.16.0 on Paper 1.18.x

### Expected behavior

SkBee loads

### SkBee Version

2.16.0

### Server Version

Paper 1.18.2

### SkBee Info

Unavailable since plugin isn't loading.

### Additional Information

Error:
```
[01:22:50] [Server thread/INFO]: [SkBee] Enabling SkBee v2.16.0
[01:22:50] [Server thread/ERROR]: Error occurred while enabling SkBee v2.16.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/block/BellRingEvent
    at com.shanebeestudios.skbee.elements.other.events.OtherEvents.<clinit>(OtherEvents.java:441) ~[SkBee-2.16.0.jar:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:467) ~[?:?]
    at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117) ~[Skript-2.6.3.jar:?]
    at com.shanebeestudios.skbee.AddonLoader.loadOtherElements(AddonLoader.java:301) ~[SkBee-2.16.0.jar:?]
    at com.shanebeestudios.skbee.AddonLoader.loadSkriptElements(AddonLoader.java:90) ~[SkBee-2.16.0.jar:?]
    at com.shanebeestudios.skbee.AddonLoader.canLoadPlugin(AddonLoader.java:80) ~[SkBee-2.16.0.jar:?]
    at com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:52) ~[SkBee-2.16.0.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.block.BellRingEvent
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
    ... 19 more
[01:22:50] [Server thread/INFO]: [SkBee] Disabling SkBee v2.16.0
```

**Comment by ShaneBeee** [comment] 2023-08-03 01:30
duplicate of #455

**Closed by ShaneBeee** 2023-08-03 01:30 UTC

**Comment by not-3than** [comment] 2023-08-03 01:40
> duplicate of #455

Where can I get the updated/fixed version of 2.16.0? I don't know how to compile it (if that's even the right word) on my own.

**Comment by ShaneBeee** [comment] 2023-08-03 01:41
assuming you're on skUnity discord, go into #general and you will see it there, its one of the last few messages from me

**Comment by not-3than** [comment] 2023-08-03 01:42
ok, thanks. some other guy sent it to me but i dont know him enough to trust its not backdoored or something, lol
