### ISSUE TITLE
[BUG] Long NBT error when setting tag

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#546] opened 2024-01-02 03:56 UTC
### What happened?

```
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! [Skript] Severe Error:
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[21:53:32 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[21:53:32 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! Stack trace:
[21:53:32 ERROR]: #!#! com.shanebeestudios.skbee.api.nbt.NbtApiException: [?][2.12.2-SNAPSHOT]Exception while getting NBT subcompounds!
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.getSubNBTTagCompound(NBTReflectionUtil.java:324)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.gettoCompount(NBTReflectionUtil.java:380)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.valideCompound(NBTReflectionUtil.java:367)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.getResolvedObject(NBTCompound.java:104)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.getData(NBTReflectionUtil.java:621)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.getType(NBTCompound.java:1348)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.addCompound(NBTCompound.java:765)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.getOrCreateCompound(NBTCompound.java:805)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.resolveOrCreateCompound(NBTCompound.java:1274)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTApi.getNestedCompound(NBTApi.java:117)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTApi.setTag(NBTApi.java:436)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprTagOfNBT.change(ExprTagOfNBT.java:153)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[21:53:32 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:53:32 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:53:32 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:53:32 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[21:53:32 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[21:53:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:538)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2009)
[21:53:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[21:53:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[21:53:32 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1485)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1462)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1385)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.bu(IAsyncTaskHandler.java:114)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1577)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1235)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[21:53:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[21:53:32 ERROR]: #!#! Caused by: com.shanebeestudios.skbee.api.nbt.NbtApiException: [?][2.12.2-SNAPSHOT]Tried getting invalid compound '-15_-60_8' from '{-10_-60_2:{custom:{info:{generator:1b,owner:"970b6af5-7990-4a6c-be1a-c1ff5a7c70f1",tier:"1"}},id:"minecraft:dirt",x:-10,y:-60,z:2},-12_-60_2:{custom:{info:{generator:1b,owner:"970b6af5-7990-4a6c-be1a-c1ff5a7c70f1",tier:"1"}},id:"minecraft:dirt",x:-12,y:-60,z:2}}'!
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.getSubNBTTagCompound(NBTReflectionUtil.java:321)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.gettoCompount(NBTReflectionUtil.java:380)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.valideCompound(NBTReflectionUtil.java:367)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.getResolvedObject(NBTCompound.java:104)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.getData(NBTReflectionUtil.java:621)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.getType(NBTCompound.java:1348)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.addCompound(NBTCompound.java:765)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.getOrCreateCompound(NBTCompound.java:805)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.resolveOrCreateCompound(NBTCompound.java:1274)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTApi.getNestedCompound(NBTApi.java:117)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.api.nbt.NBTApi.setTag(NBTApi.java:436)
[21:53:32 ERROR]: #!#!     at SkBee-3.0.1.jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprTagOfNBT.change(ExprTagOfNBT.java:153)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[21:53:32 ERROR]: #!#!     at Skript-2.7.3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[21:53:32 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:53:32 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:53:32 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:53:32 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[21:53:32 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[21:53:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:538)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2009)
[21:53:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[21:53:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[21:53:32 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1485)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1462)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1385)
[21:53:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.bu(IAsyncTaskHandler.java:114)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1577)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1235)
[21:53:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[21:53:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! Version Information:
[21:53:32 ERROR]: #!#!   Skript: 2.7.3 (OUTDATED)
[21:53:32 ERROR]: #!#!     Flavor: skriptlang-github
[21:53:32 ERROR]: #!#!     Date: 15:29:36.833117400
[21:53:32 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[21:53:32 ERROR]: #!#!   Minecraft: 1.20.4
[21:53:32 ERROR]: #!#!   Java: 17.0.3.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.3.1+2-LTS-6)
[21:53:32 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! Server platform: Paper
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! Current node: null
[21:53:32 ERROR]: #!#! Current item: set tag "custom;info;generator" of {_nbt} (as com.shanebeestudios.skbee.api.nbt.NBTCompound) to [[boolean:true]]
[21:53:32 ERROR]: #!#! Current trigger: right click (rightclick) (generator\functionality.sk, line 17)
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! Thread: Server thread
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! Language: english
[21:53:32 ERROR]: #!#! Link parse mode: DISABLED
[21:53:32 ERROR]: #!#! 
[21:53:32 ERROR]: #!#! End of Error.
[21:53:32 ERROR]: #!#! 
```

### Steps to reproduce

```
on right click:
  isBlockGenerator(event-block) = true
  if getGeneratorOwner(event-block) != player's uuid:
    send action bar "&cFuck you, this isn't your generator" to player
    cancel event
    stop
  set {_tier} to int tag "custom;info;tier" of (nbt of event-block)
  if isGeneratorUpgradable({_tier}) = false:
    send action bar "&cFuck you, this generator isn't upgradable" to player
    cancel event
    stop
  if getUpgradeCost({_tier}) > player's bal:
    send action bar "&cFuck you, you don't have enough money" to player
    cancel event
    stop
  
  set event-block to {generators::%{_tier} + 1%}
  set {_nbt} to nbt of event-block
  set tag "custom;info;generator" of {_nbt} to true
  set string tag "custom;info;owner" of {_nbt} to player's uuid
  set int tag "custom;info;tier" of {_nbt} to {_tier} + 1
  send action bar "&aFuck you, you upgraded a generator" to player
  ```
  
  This was the code I used (Ignore the messages please.), I'm unsure why it's happening.

### Expected behavior

I expected the nbt of the block to be properly set, instead it 

### SkBee Version

3.0.1

### Server Version

1.20.4

### SkBee Info

```
[21:56:26 INFO]: --- [SkBee Loading Info] ---
[21:56:26 INFO]: - [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
[21:56:26 INFO]: - [NBTAPI] NMS support 'MC1_20_R3' loaded!
[21:56:26 INFO]: - NBT Elements successfully loaded
[21:56:26 INFO]: - Text Component Elements successfully loaded
[21:56:26 INFO]: - Advancement Elements successfully loaded
[21:56:26 INFO]: - BossBar Elements successfully loaded
[21:56:26 INFO]: - Bound Elements successfully loaded
[21:56:26 INFO]: - Display Entity elements successfully loaded
[21:56:26 INFO]: - Fishing elements successfully loaded
[21:56:26 INFO]: - Game Event Elements successfully loaded
[21:56:26 INFO]: - Particle Elements successfully loaded
[21:56:26 INFO]: - RayTrace elements successfully loaded
[21:56:26 INFO]: - Recipe Elements successfully loaded
[21:56:26 INFO]: - Scoreboard Elements successfully loaded
[21:56:26 INFO]: - Scoreboard Objective Elements successfully loaded
[21:56:26 INFO]: - Statistic Elements successfully loaded
[21:56:26 INFO]: - Structure Elements successfully loaded
[21:56:26 INFO]: - Minecraft Tag elements successfully loaded
[21:56:26 INFO]: - Team Elements successfully loaded
[21:56:26 INFO]: - Villager Elements successfully loaded
[21:56:26 INFO]: - Virtual Furnace Elements disabled via config
[21:56:26 INFO]: - World Border Elements successfully loaded
[21:56:26 INFO]: - World Creator Elements successfully loaded
[21:56:26 INFO]: - Plugin is up to date!
[21:56:26 INFO]: --- [Server Info] ---
[21:56:26 INFO]: Server Version: git-Purpur-2113 (MC: 1.20.4)
[21:56:26 INFO]: Skript Version: 2.7.3
[21:56:26 INFO]: Skript Addons:
[21:56:26 INFO]: - skript-gui v1.3
[21:56:26 INFO]: - skript-reflect v2.4-dev1
[21:56:26 INFO]: SkBee Version: 3.0.1
[21:56:26 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

**Comment by ShaneBeee** [comment] 2024-01-02 07:14
Duplicate of #544

**Closed by ShaneBeee** 2024-01-02 07:14 UTC
