### ISSUE TITLE
Issue with ExprInvName

### ISSUE THREAD

**Issue by Louuuwh** [ShaneBeee/SkBee#9] opened 2020-04-28 19:56 UTC
Hey !

I'm on Paper-226 (lastest currently for 1.15.2), with Skript 2.4.1 and SkBee 1.2.0

When I use this, it does not work :
`inventory name of player's current inventory`

But when I use this, it works :
`inv name of player's current inventory`

I have neither a skript error nor an error in the console.
I don't know where it came from.

**Comment by ShaneBeee** [comment] 2020-04-28 20:37
Any chance you are using SkQuery?
I was recently told by someone I think the SkQuery syntax is the same and overrides SkBee.

**Comment by Louuuwh** [comment] 2020-04-29 03:42
Yes, I’m using SkQuery in the lastest version.

From what I can see on SkQuery github (https://github.com/SkQuery/SkQuery/blob/master/src/main/java/com/w00tmast3r/skquery/elements/expressions/ExprinventorynName.java), you’re right.

In fact, I also found that from versions 1.13+, it displays a error message that is no longer possible. Yet you do it very well on your addon. I don't understand.

Maybe we should talk to the developer of SkQuery ?

**Comment by ShaneBeee** [comment] 2020-04-29 03:46
> In fact, I also found that from versions 1.13+, it displays a error message that is no longer possible. Yet you do it very well on your addon. I don't understand.

I'm not exactly sure what your point is here.

> Maybe we should talk to the developer of SkQuery ?

If you want to, go for it. SkBee works as intended. I don't see any issue.
If you are using SkQuery and the expression overrides, then you use `inv` rather than `inventory`, I put it there for a reason.

I'm closing this as there really is no issue.

**Closed by ShaneBeee** 2020-04-29 03:46 UTC
