### ISSUE TITLE
Error tab completer clear all

### ISSUE THREAD

**Issue by Lennord** [ShaneBeee/SkBee#60] opened 2020-10-07 08:05 UTC
Hello, I have an error when I remove all tab commands...

Version Spigot: 1.16.3
Version SkBee: 1.7.0
Error console: https://pastebin.com/nDpzBeUQ

Code:

on tab complete:
	clear tab completions

**Comment by ShaneBeee** [comment] 2020-10-07 19:09
What exactly are you doing that is causing this error?
I tried your exact code and it works as intended

**Comment by Lennord** [comment] 2020-10-08 04:40
> What exactly are you doing that is causing this error?
> I tried your exact code and it works as intended

It is when I tab on the console that there is an error...

**Comment by ShaneBeee** [comment] 2020-10-08 05:05
Does this error occur in game as well or just in console?
Does it happen with all commands or just specific ones?

The more details you give here the better. So far I am unable to replicate this issue.

**Comment by Lennord** [comment] 2020-10-08 05:10
> Does this error occur in game as well or just in console?
> Does it happen with all commands or just specific ones?
> 
> The more details you give here the better. So far I am unable to replicate this issue.

The error is that on the console, and when I press the tab on the console without anything written to the console, it shows me this error. Also I haven't told you but I'm with the very last version of skript (2.5 Latest release).

**Comment by ShaneBeee** [comment] 2020-10-08 05:23
Ok I see what you mean now, Ill do my best to get this fixed.

**Comment by Lennord** [comment] 2020-10-08 05:25
> Ok I see what you mean now, Ill do my best to get this fixed.

Ok, thanks...

**Comment by Lennord** [comment] 2020-10-14 06:29
Hello, there is a problem again except that it is the players who have this bug, when I do the same code, the code does not remove the tab...

![2020-10-14_08 26 01](https://user-images.githubusercontent.com/65398078/95951826-5d664a00-0df7-11eb-91a9-5a46bcd14171.png)

Code:

on tab complete:
	clear tab completions

**Comment by ShaneBeee** [comment] 2020-10-14 10:00
those aren't tab completions, those are commands.

**Comment by Lennord** [comment] 2020-10-14 11:05
> those aren't tab completions, those are commands.

Ok but how do you remove these commands from the list?

**Comment by ShaneBeee** [comment] 2020-10-14 11:08
Thats managed by the commands and permissions

**Comment by Lennord** [comment] 2020-10-14 11:34
> Thats managed by the commands and permissions

Ok thanks ;)

**Comment by ShaneBeee** [comment] 2020-10-15 01:58
closing this, I forgot to close it when I released the update.

**Closed by ShaneBeee** 2020-10-15 01:58 UTC
Labels: bug, completed
