### ISSUE TITLE
[BUG] Failed to startup

### ISSUE THREAD

**Issue by Samaine** [ShaneBeee/SkBee#144] opened 2022-03-13 08:38 UTC
**To Reproduce**
While starting the server

**Screenshots/Errors**
```[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! [Skript] Severe Error:
[17:35:08 ERROR]: #!#! SkBee's class com.shanebeestudios.skbee.elements.board.type.Types generated an exception while loading
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! Something went horribly wrong with Skript.
[17:35:08 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:35:08 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:35:08 ERROR]: #!#! Following plugins are probably related to this error in some way:
[17:35:08 ERROR]: #!#! SkBee (https://github.com/ShaneBeee/SkBee)
[17:35:08 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:35:08 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:35:08 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:35:08 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:35:08 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! Stack trace:
[17:35:08 ERROR]: #!#! java.lang.IllegalArgumentException: Can't register org.bukkit.scoreboard.Team$Option with the code name teamoption because that name is already used by team options
[17:35:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:90)
[17:35:08 ERROR]: #!#!     at SkBee-1.15.1.jar//com.shanebeestudios.skbee.elements.board.type.Types.<clinit>(Types.java:20)
[17:35:08 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[17:35:08 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[17:35:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[17:35:08 ERROR]: #!#!     at SkBee-1.15.1.jar//com.shanebeestudios.skbee.SkBee.loadBoardElements(SkBee.java:177)
[17:35:08 ERROR]: #!#!     at SkBee-1.15.1.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:102)
[17:35:08 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:35:08 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:35:08 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:35:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[17:35:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[17:35:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[17:35:08 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[17:35:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[17:35:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:35:08 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! Version Information:
[17:35:08 ERROR]: #!#!   Skript: 2.6.1 (latest)
[17:35:08 ERROR]: #!#!     Flavor: skriptlang-github
[17:35:08 ERROR]: #!#!     Date: 22:18:42.554713200
[17:35:08 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[17:35:08 ERROR]: #!#!   Minecraft: 1.17.1
[17:35:08 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[17:35:08 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! Server platform: Paper
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! Current node: null
[17:35:08 ERROR]: #!#! Current item: null
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! Thread: Server thread
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! Language: english
[17:35:08 ERROR]: #!#! Link parse mode: DISABLED
[17:35:08 ERROR]: #!#!
[17:35:08 ERROR]: #!#! End of Error.
[17:35:08 ERROR]: #!#!```

**Version Info:**
 - **SkBee Version:** 1.15.1
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** Paper 1.17.1

**Comment by ShaneBeee** [comment] 2022-03-20 13:21
Duplicate of #137

**Closed by ShaneBeee** 2022-03-20 13:21 UTC
